### ISSUE TITLE
resp. Sufficiebat nobis - typos

### ISSUE THREAD

**Issue by igneus** [Nocturnale-Romanum/nocturnale-romanum#2]
Looking at contents of the pdf committed in this repository I stumbled upon a responsory with typos (not present in Sandhofe) https://nocturnale.marteo.fr/chant/09H3N2R1/ It should be:

Sufficiébat nobi**s** paupértas nostra, ut divíti**as** computarémus

I'm not sure what the correct procedure for submitting such fixes is, since gabc files don't seem to be included in any of the project's repositories. I registered on https://nocturnale.marteo.fr/ and tried the "Create my proposal" button for this chant, but the proposal form only supports inserting whole new gabc without providing access to the current one, i.e. it basically requires transcribing the whole responsory anew.

**Comment by xmarteo** [comment]
https://nocturnale.marteo.fr/ is still in preliminary development. A "clone this proposal into mine" feature is on the roadmap.

The "sandhofe" proposals on https://nocturnale.marteo.fr/ are imports from Gregobase (scripted but not cron'd, done more or less monthly) - the cross-table between the "Hudelmaier code" (09H3N2R1 in this example) and the Gregobase chant_id is here: https://docs.google.com/spreadsheets/d/1o5Y3dil_2c8xRLG8awUvMuJYTmPRwgIdt0jvM_3r-94/

Therefore, errors in "sandhofe" proposals should be fixed in Gregobase.

I really should document this whole thing. I'll try and do it some time this week.

**Comment by igneus** [comment]
> Therefore, errors in "sandhofe" proposals should be fixed in Gregobase

Great, thanks, will do so.

**Comment by xmarteo** [comment]
Yes, "nobi" was clearly a typo but I think "divitiae" is correct.
On a side note, do you think the website should handle the text separately from the music (i.e. have a "text" field for each chant instead of just a bunch of GABC proposals), and check the conformity of proposals to the text?
In both cases, what would be the right way for people to report typos in the text? I like GitHub tickets, but not everyone has an account. I am not keen on implementing yet another ticket system on the website but it might come to that.

**Comment by igneus** [comment]
> On a side note, do you think the website should handle the text separately from the music (i.e. have a "text" field for each chant instead of just a bunch of GABC proposals), and check the conformity of proposals to the text?

While such an approach may make sense in case of fixing mere typos, I find it risky. The connection between music and lyrics in Gregorian chant is (not always, but often) intimate, reliably "checking the conformity of [music] proposals to the text" in a fully automated way is non-trivial (if possible at all) and a possibility to edit the text on its own may easily lead to breaking the intimate connection between music and lyrics without anyone noticing.

Also, it's very probable that there will be cases of chants where different proposals will have slightly (or less slightly) different lyrics and where the editorial decision will be not only "take tune A or tune B", but also "take an ancient tune at the cost of lyrics diverging from the breviary, or take (or compose/adjust) a newer one, matching the text of the post-Tridentine typical editions?"

> In both cases, what would be the right way for people to report typos in the text? I like GitHub tickets, but not everyone has an account.

Github accounts are free and easy to create, so I don't see any issue there. Many non-developers have signed up on Github just in order to be able to report issues for https://www.divinumofficium.com/ . For people seeing value in this project and willing to contribute to it it will be no greater obstacle than for the Divinum Officium folks.

For typos in scores imported from GregoBase the "please go to GregoBase and fix it there" approach is just OK. But cases like this one, where we are already beginning to correct Sandhofe, are controversial. I wouldn't find it right to change the GregoBase score, which is declared to be a transcription from Sandhofe's Nocturnale Romanum, to different lyrics - even if these may be actually "more correct".

**Comment by leduc006** [comment]
If anyone has an online source for the editio typica text, I would certainly appreciate having it! 

Agreed nobi is a typo which I will repair presently in Gregobase.  My other sources (cited below) also have computarentur rather than Sandhofe's computaremus.  But divitiae seems right.

I do not have a strict editio typica; I confirmed divitiae in accordance with my breviary, which is from Liturgical Press, Collegeville MN "The Hours of the Divine Office in English and Latin", 1964 "in accord with the editio typica".  This R occurs Tuesday in Week 3 of Sept in the post 1962 rubrics.  It is also what appears in the Cantus database as the 'standardized text' for this text.  Finally, there is a pre-1960 monastic rite breviary online at the internet archive (archive.org) which has divitiae for R4 3rd Sunday in Sept, pg. 307 (but editio altera).  https://archive.org/details/breviarium-monasticum-pars-ii/Breviarium%20Monasticum%20-%20Pars%20II/

As to having a separate text field - not sure.  Regarding error checking: there would be questions as to whether the plain text matched the text in the gabc unless the latter were programmatically prepared from the former; then there is the question of accents, punctuation, etc.  It could be done, I suppose, but not sure if it is easier than just comparing the representation/pdf of the gabc to the printed text, unless we had some way to have the actual text to do machine-based comparisons.   

Whether or not a separate text field with just text would be helpful for doing text searches is a possibility, but not sure it is worth the effort?  If it can be prepared programmatically from the gabc, stripping accents and with case-insensitive searching, maybe so as part of the final 'product'.  But not sure it is helpful in preparing the book.

**Comment by leduc006** [comment]
Above I actually meant 'former prepared from the latter'.  On the surface, it seems it would not be too difficult to programmatically take a gabc file and extract the text by discarding stuff between parentheses and square brackets.  The <v> and <sp> tags may add a wrinkle.  Some people in Gregobase cut and paste their own V/ and R/ symbols from a font which does not display universally.  And the further down the rabbit hole you go, the more minor challenges one can expect.  

Someone out there wrote a utility for matching text to gabc note clusters.  So you could, for example, typeset the notes of a single verse of a hymn in gabc and then merge text from a separate file to the note blocks.  Not sure how it handles syllabification - I guess maybe you are just typing separate syllables in that case.  I thought about using it for hymns, but it seemed more trouble to learn than just typing out the hymns.

**Comment by leduc006** [comment]
Maybe I didn't do the right thing, but I just dropped a 'my version' into git hub with the 'corrected' text and otherwise unchanged from Sandhofe.  Feel free to delete it if this is not helpful.  I am also a git hub novice.  Even less than novice.

**Comment by xmarteo** [comment]
@leduc006 You did not drop your version into GitHub (this website) but into http://nocturnale.marteo.fr/ , which is the right thing to do, except the site is not in a "production stage" but rather publicly available for people to request features and suggest better implementation / layout of existing features.
